version: 2.1
orbs:
  android: circleci/android@1.0.3

jobs:
  build-and-test:
    executor:
      name: android/android-machine

    steps:
      - checkout
      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run App Module Unit Test
          command: ./gradlew clean test
      - store_artifacts:
          path: :app:build:reports
      - store_test_results:
          path: :app:build:test-results
      - run:
          name: Run Build
          command: ./gradlew build

workflows:
  sample:
    jobs:
      - build-and-test
