package com.bagusmerta.utility

enum class LanguageEnum(val isoCode: String) {
    ENGLISH("en"),
    SPANISH("es"),
    FRENCH("fr"),
    GERMAN("de"),
    CHINESE("zh"),
    JAPANESE("ja"),
    ARABIC("ar"),
    RUSSIAN("ru"),
    PORTUGUESE("pt"),
    ITALIAN("it"),
    DUTCH("nl"),
    KOREAN("ko"),
    TURKISH("tr"),
    POLISH("pl"),
    SWEDISH("sv"),
    DANISH("da"),
    NORWEGIAN("no"),
    FINNISH("fi"),
    GREEK("el"),
    HINDI("hi"),
    HEBREW("he"),
    THAI("th"),
    VIETNAMESE("vi"),
    INDONESIAN("id"),
    MALAY("ms"),
    CZECH("cs"),
    HUNGARIAN("hu"),
    ROMANIAN("ro"),
    UKRAINIAN("uk"),
    BULGARIAN("bg"),
    CROATIAN("hr"),
    SERBIAN("sr"),
    SLOVAK("sk"),
    SLOVENIAN("sl"),
    LITHUANIAN("lt"),
    LATVIAN("lv"),
    ESTONIAN("et"),
    ICELANDIC("is"),
    MALTESE("mt"),
    IRISH("ga"),
    WELSH("cy"),
    SCOTS_GAELIC("gd"),
    // ... Add more languages here

    // Default language in case the code is not found
    UNKNOWN("unknown")
}
